### ISSUE TITLE
About the license of this project

### ISSUE THREAD

**Issue by ghost** [MewX/cross-channel_chinesizing_project#1]
*Seems the repo maintainer speaks Chinese, so I'll also write Chinese for the issue.
Apologizes for the inconveniences (if any)*

----------
关于repo的license提个小的建议：
1. license最好作为**单独的文件**添加进repo，而不是写在README里面，这样会更加一目了然的显示在repo的信息栏上，可以参考GitHub官方的说明 [Licensing a repository](https://help.github.com/articles/licensing-a-repository/)：

> Some projects include information about their license in their README. For example, a project's README may include a note saying "This project is licensed under the terms of the MIT license."
> 
> As a best practice, we encourage you to include the license file with your project.

2. 对于Apache license来说，开头的Copyright year和owner**需要替换成项目公开的时间和license owner的名字**；关于这一点可以参照[Apache license官网的解释](https://www.apache.org/licenses/LICENSE-2.0.html#apply)；或者，一个更方便的办法是直接使用 [GitHub原生的license templates](https://help.github.com/articles/adding-a-license-to-a-repository/) 添加license

最后感谢汉化组大佬们的努力！以及祝大家新年快乐XD

**Comment by MewX** [comment]
新年快乐！
谢谢反馈，有兴趣提交pull request来修一下吗？ 😉

**Comment by ghost** [comment]
好的呀，我改完直接PR

**Comment by MewX** [comment]
Merged
