### ISSUE TITLE
更新域名，需要买到合适的国际域名长期使用

### ISSUE THREAD

**Issue by MewX** [MewX/cross-channel_chinesizing_project#9]
近日 `.cn` 域名总给我一种不靠谱的感觉，绑定澳洲手机号的账号全叫我上传身份证照片。明明我之前绑定的就是国内手机号，只不过换了一下就这样。

我觉得我需要提前开始打算这个transition。

简单查了一下，常用的com org net域名都被注册了。。。慢慢看吧就

**Comment by jianrry** [comment]
https://www.namesilo.com/domain/search-domains?query=crosschannel

还有很多后缀可以注册，大多数是小众后缀．

你可以考虑一下crosschannel.in，$6.89 就可以买到，每年续费的价格也是$6.89．

**Comment by MewX** [comment]
@jianrry .in是印度的域名，又陷入了.cn域名的尴尬境地

**Comment by MewX** [comment]
买到了 https://crosschannel.games

**Comment by MewX** [comment]
更新完毕，估计CN域名下个月就不续费了
